package net.liftmodules.mapperauth.model

import net.liftweb._
import net.liftweb.common._
import net.liftweb.http._
import net.liftweb.mapper.LongKeyedMapper
import net.liftweb.mapper.IdPK
import net.liftweb.mapper.LongKeyedMetaMapper
import net.liftweb.util.Helpers._
import net.liftweb.mapper.By
import net.liftweb.mapper.MappedLongForeignKey
import net.liftmodules.mapperauth.model.share.MappedExpiringDate
import net.liftmodules.mapperauth.MapperAuth
import net.liftweb.mapper.MappedLong
import net.liftweb.mapper.KeyedMapper
import net.liftweb.mapper.KeyedMetaMapper
import net.liftweb.mapper.MappedStringIndex
import java.util.UUID

/**
  * This is a token for automatically logging a user in
  */
class LoginToken extends KeyedMapper[String, LoginToken] {
  def getSingleton = LoginToken
  def primaryKeyField = id

  object id extends MappedStringIndex(this, 100) {
    override def writePermission_? = true
    override def dbAutogenerated_? = false
    override def dbNotNull_? = true
    override def dbIndexed_? = true
  }

  object userId  extends MappedLong(this) {
    override def dbIndexed_? = true
  }

  object expires extends MappedExpiringDate(this, getSingleton.loginTokenExpires)

  def url: String = getSingleton.url(this)
}


object LoginToken extends LoginToken with KeyedMetaMapper[String, LoginToken] {

  override def dbTableName = "logintokens"

  private lazy val loginTokenUrl = MapperAuth.loginTokenUrl.vend
  private lazy val loginTokenExpires = MapperAuth.loginTokenExpires.vend

  def url(inst: LoginToken): String = "%s%s?token=%s".format(S.hostAndPath, loginTokenUrl, inst.id)

  def createForUserId(uid: Long): LoginToken = {
    create.id(UUID.randomUUID().toString()).userId(uid).saveMe
  }

  def deleteAllByUserId(uid: Long) {
    this.find(By(userId, uid)).foreach(_.delete_!)
  }

  def findByStringId(in: String): Box[LoginToken] =
    try {
      find(By(LoginToken.id, in))
    } catch {
      case e: Exception => Failure("Invalid Id: "+in)
    }

}
